// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace TrainBooking.DAL.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TicketPrice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TicketPrice));
        
        string IMigrationMetadata.Id
        {
            get { return "201509231113284_TicketPrice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
